"""Create database schema

Revision ID: 317322cd0e8d
Revises: bff3546daeb7
Create Date: 2026-04-03 18:09:47.594188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '317322cd0e8d'
down_revision = 'bff3546daeb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room',
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('room_id')
    )
    op.create_table('ticket_type',
    sa.Column('ticket_type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('ticket_type_id')
    )
    op.create_table('tool',
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('tool_id')
    )
    op.create_table('ticket_type_tool',
    sa.Column('ticket_type_id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_type_id'], ['ticket_type.ticket_type_id'], ),
    sa.ForeignKeyConstraint(['tool_id'], ['tool.tool_id'], ),
    sa.PrimaryKeyConstraint('ticket_type_id', 'tool_id')
    )
    op.create_table('tool_order',
    sa.Column('tool_order_id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('details', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('ordered', 'ready', name='toolorderstatus'), nullable=False),
    sa.ForeignKeyConstraint(['tool_id'], ['tool.tool_id'], ),
    sa.PrimaryKeyConstraint('tool_order_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('student', 'admin', 'maintainer', 'maintenance_manager', name='userrole'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['room.room_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('ticket',
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('maintainer_id', sa.Integer(), nullable=False),
    sa.Column('ticket_type_id', sa.Integer(), nullable=False),
    sa.Column('details', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('in_progress', 'done', name='ticketstatus'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.CheckConstraint('priority >= 0 AND priority <= 5', name='check_ticket_priority'),
    sa.ForeignKeyConstraint(['maintainer_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['room.room_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['ticket_type_id'], ['ticket_type.ticket_type_id'], ),
    sa.PrimaryKeyConstraint('ticket_id')
    )
    op.create_table('student_feedback',
    sa.Column('student_feedback_id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('details', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.ticket_id'], ),
    sa.PrimaryKeyConstraint('student_feedback_id'),
    sa.UniqueConstraint('ticket_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_feedback')
    op.drop_table('ticket')
    op.drop_table('user')
    op.drop_table('tool_order')
    op.drop_table('ticket_type_tool')
    op.drop_table('tool')
    op.drop_table('ticket_type')
    op.drop_table('room')
    # ### end Alembic commands ###
