"""Add created_by and created_at to ToolOrder

Revision ID: 643dcfc6b0cf
Revises: 6ccbfadd1b2d
Create Date: 2026-05-02 16:09:00.071097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '643dcfc6b0cf'
down_revision = '6ccbfadd1b2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tool_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.create_foreign_key('fk_tool_order_created_by_id', 'user', ['created_by_id'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tool_order', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tool_order_created_by_id', type_='foreignkey')
        batch_op.drop_column('created_at')
        batch_op.drop_column('created_by_id')

    # ### end Alembic commands ###
