"""update ticket status and soft delete

Revision ID: 6ccbfadd1b2d
Revises: bb344d3633ce
Create Date: 2026-04-08 17:55:06.148446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ccbfadd1b2d'
down_revision = 'bb344d3633ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.Enum('in_progress', 'ready_to_done', 'done', name='ticketstatus'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('in_progress', 'ready_to_done', 'done', name='ticketstatus'),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###
